// drinks/models/drink.mock.ts
import { Drink } from './drink.model';

export const MOCK_DRINKS: Drink[] = [
  {
    _id: '6650a1b2c3d4e5f6a7b8c901',
    name: 'Cuban Mojito',
    category: 'Classic Cocktail',
    baseSpirit: 'White Rum',
    glassware: 'Highball',
    garnish: 'Mint + Lime Wheel',
    servingSize: 350,
    status: true,
    preparation: 'Muddle mint and lime, add rum and sugar, top with soda water. Stir gently.',
    notes: 'Use fresh mint only. Never use dried mint.',
    ingredients: [
      { name: 'White Rum', quantity: 60, unit: 'ml' },
      { name: 'Fresh Lime Juice', quantity: 30, unit: 'ml' },
      { name: 'Simple Syrup', quantity: 20, unit: 'ml' },
      { name: 'Soda Water', quantity: 90, unit: 'ml' },
      { name: 'Mint Leaves', quantity: 8, unit: 'leaves' },
      { name: 'Lime Wedge', quantity: 2, unit: 'slice' },
    ],
  },
  {
    _id: '6650a1b2c3d4e5f6a7b8c902',
    name: 'Piña Colada',
    category: 'Tropical',
    baseSpirit: 'White Rum',
    glassware: 'Hurricane Glass',
    garnish: 'Pineapple Slice + Cherry',
    servingSize: 400,
    status: true,
    preparation: 'Blend all ingredients with ice until smooth. Serve in hurricane glass.',
    notes: '',
    ingredients: [
      { name: 'White Rum', quantity: 60, unit: 'ml' },
      { name: 'Coconut Cream', quantity: 45, unit: 'ml' },
      { name: 'Pineapple Juice', quantity: 120, unit: 'ml' },
      { name: 'Ice', quantity: 1, unit: 'unit' },
    ],
  },
  {
    _id: '6650a1b2c3d4e5f6a7b8c903',
    name: 'Margarita',
    category: 'Spirit-Based',
    baseSpirit: 'Tequila',
    glassware: 'Margarita Glass',
    garnish: 'Lime Wheel + Salt Rim',
    servingSize: 300,
    status: true,
    preparation: 'Shake tequila, triple sec, and lime juice with ice. Strain into salt-rimmed glass.',
    notes: 'Salt rim is optional per client preference.',
    ingredients: [
      { name: 'Tequila', quantity: 60, unit: 'ml' },
      { name: 'Triple Sec', quantity: 30, unit: 'ml' },
      { name: 'Fresh Lime Juice', quantity: 30, unit: 'ml' },
      { name: 'Salt', quantity: 1, unit: 'dash' },
    ],
  },
  {
    _id: '6650a1b2c3d4e5f6a7b8c904',
    name: 'Old Fashioned',
    category: 'Classic Cocktail',
    baseSpirit: 'Whiskey',
    glassware: 'Rocks Glass',
    garnish: 'Orange Peel',
    servingSize: 120,
    status: true,
    preparation: 'Muddle sugar with bitters, add whiskey and ice, stir gently. Garnish with orange peel.',
    notes: '',
    ingredients: [
      { name: 'Bourbon Whiskey', quantity: 60, unit: 'ml' },
      { name: 'Simple Syrup', quantity: 10, unit: 'ml' },
      { name: 'Angostura Bitters', quantity: 2, unit: 'dash' },
      { name: 'Orange Peel', quantity: 1, unit: 'unit' },
    ],
  },
  {
    _id: '6650a1b2c3d4e5f6a7b8c905',
    name: 'Grinch Punch',
    category: 'Holiday',
    baseSpirit: 'Vodka',
    glassware: 'Punch Glass',
    garnish: 'Cherry',
    servingSize: 250,
    status: false,
    preparation: 'Mix all ingredients in a punch bowl. Serve chilled over ice.',
    notes: 'Seasonal drink — December only.',
    ingredients: [
      { name: 'Vodka', quantity: 45, unit: 'ml' },
      { name: 'Midori', quantity: 30, unit: 'ml' },
      { name: 'Lemon Juice', quantity: 20, unit: 'ml' },
      { name: 'Sprite', quantity: 100, unit: 'ml' },
      { name: 'Cherry', quantity: 1, unit: 'unit' },
    ],
  },
  {
    _id: '6650a1b2c3d4e5f6a7b8c906',
    name: 'Virgin Sunrise',
    category: 'Mocktail',
    baseSpirit: 'None / Non-Alcoholic',
    glassware: 'Highball',
    garnish: 'Orange Slice',
    servingSize: 280,
    status: true,
    preparation: 'Layer orange juice over ice, slowly pour grenadine to create sunrise effect.',
    notes: 'Great non-alcoholic option for corporate events.',
    ingredients: [
      { name: 'Orange Juice', quantity: 180, unit: 'ml' },
      { name: 'Grenadine', quantity: 30, unit: 'ml' },
      { name: 'Ice', quantity: 1, unit: 'unit' },
    ],
  },
  {
    _id: '6650a1b2c3d4e5f6a7b8c907',
    name: 'Daiquiri',
    category: 'Classic Cocktail',
    baseSpirit: 'White Rum',
    glassware: 'Coupe',
    garnish: 'Lime Wheel',
    servingSize: 200,
    status: true,
    preparation: 'Shake all ingredients with ice. Double strain into chilled coupe glass.',
    notes: '',
    ingredients: [
      { name: 'White Rum', quantity: 60, unit: 'ml' },
      { name: 'Fresh Lime Juice', quantity: 25, unit: 'ml' },
      { name: 'Simple Syrup', quantity: 15, unit: 'ml' },
    ],
  },
  {
    _id: '6650a1b2c3d4e5f6a7b8c908',
    name: 'Moscow Mule',
    category: 'Spirit-Based',
    baseSpirit: 'Vodka',
    glassware: 'Copper Mug',
    garnish: 'Lime Wedge + Mint',
    servingSize: 320,
    status: true,
    preparation: 'Build in copper mug over ice. Add vodka, lime juice, top with ginger beer. Stir.',
    notes: 'Copper mug is essential for presentation.',
    ingredients: [
      { name: 'Vodka', quantity: 60, unit: 'ml' },
      { name: 'Fresh Lime Juice', quantity: 20, unit: 'ml' },
      { name: 'Ginger Beer', quantity: 150, unit: 'ml' },
    ],
  },
];
